"""add_phone_no

Revision ID: 147514bff892
Revises: 05cf291d630f
Create Date: 2024-12-11 11:15:09.128267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147514bff892'
down_revision: Union[str, None] = '05cf291d630f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_no', sa.String(), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['phone_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'phone_no')
    # ### end Alembic commands ###
